# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       voicemail-notifications

# >> macros
# << macros

%{!?qtc_qmake:%define qtc_qmake %qmake}
%{!?qtc_qmake5:%define qtc_qmake5 %qmake5}
%{!?qtc_make:%define qtc_make make}
%{?qtc_builddir:%define _builddir %qtc_builddir}
Summary:    Voicemail notifications
Version:    0.0.6
Release:    1
Group:      Qt/Qt
License:    LICENSE
URL:        http://example.org/
Source0:    %{name}-%{version}.tar.bz2
Requires:   sailfishsilica-qt5 >= 0.10.9
BuildRequires:  pkgconfig(sailfishapp) >= 1.0.2
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  desktop-file-utils

%description
Simple daemon and settings gui to show voicemail notifications


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qtc_qmake5 

%qtc_make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop


%pre
if /sbin/pidof voicemail-daemon > /dev/null; then
killall voicemail-daemon
fi

if /sbin/pidof voicemail-notifications > /dev/null; then
killall voicemail-notifications
fi

%preun
if /sbin/pidof voicemail-daemon > /dev/null; then
killall voicemail-daemon
fi

if /sbin/pidof voicemail-notifications > /dev/null; then
killall voicemail-notifications
fi

%files
%defattr(-,root,root,-)
%{_bindir}
%{_datadir}/voicemail-notifications
%{_datadir}/applications/voicemail-notifications.desktop
%{_datadir}/icons/hicolor/86x86/apps/voicemail-notifications.png
/usr/share/dbus-1/services/org.coderus.voicemailwatcher.service
/usr/lib/systemd/user/voicemail-daemon.service
# >> files
# << files
